#ifndef __H_KERNEL_darcy_support_afq_state
#define __H_KERNEL_darcy_support_afq_state

/*
 * This file autogenerated by kerngen version p7
 * Copyright 2015 
 * Alejandro Francisco Queiruga
 * Lawrence Berkeley National Lab
 */

#include "kernel.h"

extern kernel_t kernel_darcy_support_afq;

#endif