# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_hypergraph', [dirname(__file__)])
        except ImportError:
            import _hypergraph
            return _hypergraph
        if fp is not None:
            try:
                _mod = imp.load_module('_hypergraph', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _hypergraph = swig_import_helper()
    del swig_import_helper
else:
    import _hypergraph
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class intArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _hypergraph.new_intArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hypergraph.delete_intArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _hypergraph.intArray___getitem__(self, *args)
    def __setitem__(self, *args): return _hypergraph.intArray___setitem__(self, *args)
    def cast(self): return _hypergraph.intArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _hypergraph.intArray_frompointer
    if _newclass:frompointer = staticmethod(_hypergraph.intArray_frompointer)
intArray_swigregister = _hypergraph.intArray_swigregister
intArray_swigregister(intArray)

def intArray_frompointer(*args):
  return _hypergraph.intArray_frompointer(*args)
intArray_frompointer = _hypergraph.intArray_frompointer

class intp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _hypergraph.new_intp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hypergraph.delete_intp
    __del__ = lambda self : None;
    def assign(self, *args): return _hypergraph.intp_assign(self, *args)
    def value(self): return _hypergraph.intp_value(self)
    def cast(self): return _hypergraph.intp_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _hypergraph.intp_frompointer
    if _newclass:frompointer = staticmethod(_hypergraph.intp_frompointer)
intp_swigregister = _hypergraph.intp_swigregister
intp_swigregister(intp)

def intp_frompointer(*args):
  return _hypergraph.intp_frompointer(*args)
intp_frompointer = _hypergraph.intp_frompointer

class hypergraph_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, hypergraph_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, hypergraph_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["n_edge"] = _hypergraph.hypergraph_t_n_edge_set
    __swig_getmethods__["n_edge"] = _hypergraph.hypergraph_t_n_edge_get
    if _newclass:n_edge = _swig_property(_hypergraph.hypergraph_t_n_edge_get, _hypergraph.hypergraph_t_n_edge_set)
    __swig_setmethods__["n_e_alloc"] = _hypergraph.hypergraph_t_n_e_alloc_set
    __swig_getmethods__["n_e_alloc"] = _hypergraph.hypergraph_t_n_e_alloc_get
    if _newclass:n_e_alloc = _swig_property(_hypergraph.hypergraph_t_n_e_alloc_get, _hypergraph.hypergraph_t_n_e_alloc_set)
    __swig_setmethods__["l_edge"] = _hypergraph.hypergraph_t_l_edge_set
    __swig_getmethods__["l_edge"] = _hypergraph.hypergraph_t_l_edge_get
    if _newclass:l_edge = _swig_property(_hypergraph.hypergraph_t_l_edge_get, _hypergraph.hypergraph_t_l_edge_set)
    __swig_setmethods__["edges"] = _hypergraph.hypergraph_t_edges_set
    __swig_getmethods__["edges"] = _hypergraph.hypergraph_t_edges_get
    if _newclass:edges = _swig_property(_hypergraph.hypergraph_t_edges_get, _hypergraph.hypergraph_t_edges_set)
    def __init__(self): 
        this = _hypergraph.new_hypergraph_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _hypergraph.delete_hypergraph_t
    __del__ = lambda self : None;
hypergraph_t_swigregister = _hypergraph.hypergraph_t_swigregister
hypergraph_t_swigregister(hypergraph_t)


def Hypergraph_Alloc(*args):
  return _hypergraph.Hypergraph_Alloc(*args)
Hypergraph_Alloc = _hypergraph.Hypergraph_Alloc

def Hypergraph_Push_Edge(*args):
  return _hypergraph.Hypergraph_Push_Edge(*args)
Hypergraph_Push_Edge = _hypergraph.Hypergraph_Push_Edge

def Hypergraph_Get_Edge(*args):
  return _hypergraph.Hypergraph_Get_Edge(*args)
Hypergraph_Get_Edge = _hypergraph.Hypergraph_Get_Edge

def Hypergraph_Destroy(*args):
  return _hypergraph.Hypergraph_Destroy(*args)
Hypergraph_Destroy = _hypergraph.Hypergraph_Destroy

def Hypergraph_Push_Edge_np(*args):
  return _hypergraph.Hypergraph_Push_Edge_np(*args)
Hypergraph_Push_Edge_np = _hypergraph.Hypergraph_Push_Edge_np

def Hypergraph_Get_Edge_np(*args):
  return _hypergraph.Hypergraph_Get_Edge_np(*args)
Hypergraph_Get_Edge_np = _hypergraph.Hypergraph_Get_Edge_np

def Hypergraph_Get_View_np(*args):
  return _hypergraph.Hypergraph_Get_View_np(*args)
Hypergraph_Get_View_np = _hypergraph.Hypergraph_Get_View_np
# This file is compatible with both classic and new-style classes.


