# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_mylibrary', [dirname(__file__)])
        except ImportError:
            import _mylibrary
            return _mylibrary
        if fp is not None:
            try:
                _mod = imp.load_module('_mylibrary', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _mylibrary = swig_import_helper()
    del swig_import_helper
else:
    import _mylibrary
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class intArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _mylibrary.new_intArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mylibrary.delete_intArray
    __del__ = lambda self : None;
    def __getitem__(self, *args): return _mylibrary.intArray___getitem__(self, *args)
    def __setitem__(self, *args): return _mylibrary.intArray___setitem__(self, *args)
    def cast(self): return _mylibrary.intArray_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _mylibrary.intArray_frompointer
    if _newclass:frompointer = staticmethod(_mylibrary.intArray_frompointer)
intArray_swigregister = _mylibrary.intArray_swigregister
intArray_swigregister(intArray)

def intArray_frompointer(*args):
  return _mylibrary.intArray_frompointer(*args)
intArray_frompointer = _mylibrary.intArray_frompointer

class intp(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intp, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intp, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _mylibrary.new_intp()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mylibrary.delete_intp
    __del__ = lambda self : None;
    def assign(self, *args): return _mylibrary.intp_assign(self, *args)
    def value(self): return _mylibrary.intp_value(self)
    def cast(self): return _mylibrary.intp_cast(self)
    __swig_getmethods__["frompointer"] = lambda x: _mylibrary.intp_frompointer
    if _newclass:frompointer = staticmethod(_mylibrary.intp_frompointer)
intp_swigregister = _mylibrary.intp_swigregister
intp_swigregister(intp)

def intp_frompointer(*args):
  return _mylibrary.intp_frompointer(*args)
intp_frompointer = _mylibrary.intp_frompointer

class hypergraph_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, hypergraph_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, hypergraph_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["n_edge"] = _mylibrary.hypergraph_t_n_edge_set
    __swig_getmethods__["n_edge"] = _mylibrary.hypergraph_t_n_edge_get
    if _newclass:n_edge = _swig_property(_mylibrary.hypergraph_t_n_edge_get, _mylibrary.hypergraph_t_n_edge_set)
    __swig_setmethods__["n_e_alloc"] = _mylibrary.hypergraph_t_n_e_alloc_set
    __swig_getmethods__["n_e_alloc"] = _mylibrary.hypergraph_t_n_e_alloc_get
    if _newclass:n_e_alloc = _swig_property(_mylibrary.hypergraph_t_n_e_alloc_get, _mylibrary.hypergraph_t_n_e_alloc_set)
    __swig_setmethods__["l_edge"] = _mylibrary.hypergraph_t_l_edge_set
    __swig_getmethods__["l_edge"] = _mylibrary.hypergraph_t_l_edge_get
    if _newclass:l_edge = _swig_property(_mylibrary.hypergraph_t_l_edge_get, _mylibrary.hypergraph_t_l_edge_set)
    __swig_setmethods__["edges"] = _mylibrary.hypergraph_t_edges_set
    __swig_getmethods__["edges"] = _mylibrary.hypergraph_t_edges_get
    if _newclass:edges = _swig_property(_mylibrary.hypergraph_t_edges_get, _mylibrary.hypergraph_t_edges_set)
    def __init__(self): 
        this = _mylibrary.new_hypergraph_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mylibrary.delete_hypergraph_t
    __del__ = lambda self : None;
hypergraph_t_swigregister = _mylibrary.hypergraph_t_swigregister
hypergraph_t_swigregister(hypergraph_t)


def Hypergraph_Alloc(*args):
  return _mylibrary.Hypergraph_Alloc(*args)
Hypergraph_Alloc = _mylibrary.Hypergraph_Alloc

def Hypergraph_Push_Edge(*args):
  return _mylibrary.Hypergraph_Push_Edge(*args)
Hypergraph_Push_Edge = _mylibrary.Hypergraph_Push_Edge

def Hypergraph_Get_Edge(*args):
  return _mylibrary.Hypergraph_Get_Edge(*args)
Hypergraph_Get_Edge = _mylibrary.Hypergraph_Get_Edge

def Hypergraph_Destroy(*args):
  return _mylibrary.Hypergraph_Destroy(*args)
Hypergraph_Destroy = _mylibrary.Hypergraph_Destroy
SPATIAL_HASH_MAXDIM = _mylibrary.SPATIAL_HASH_MAXDIM
class spatialhash_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, spatialhash_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, spatialhash_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["dim"] = _mylibrary.spatialhash_t_dim_set
    __swig_getmethods__["dim"] = _mylibrary.spatialhash_t_dim_get
    if _newclass:dim = _swig_property(_mylibrary.spatialhash_t_dim_get, _mylibrary.spatialhash_t_dim_set)
    __swig_setmethods__["Npart"] = _mylibrary.spatialhash_t_Npart_set
    __swig_getmethods__["Npart"] = _mylibrary.spatialhash_t_Npart_get
    if _newclass:Npart = _swig_property(_mylibrary.spatialhash_t_Npart_get, _mylibrary.spatialhash_t_Npart_set)
    __swig_setmethods__["start"] = _mylibrary.spatialhash_t_start_set
    __swig_getmethods__["start"] = _mylibrary.spatialhash_t_start_get
    if _newclass:start = _swig_property(_mylibrary.spatialhash_t_start_get, _mylibrary.spatialhash_t_start_set)
    __swig_setmethods__["h"] = _mylibrary.spatialhash_t_h_set
    __swig_getmethods__["h"] = _mylibrary.spatialhash_t_h_get
    if _newclass:h = _swig_property(_mylibrary.spatialhash_t_h_get, _mylibrary.spatialhash_t_h_set)
    __swig_setmethods__["Ncell"] = _mylibrary.spatialhash_t_Ncell_set
    __swig_getmethods__["Ncell"] = _mylibrary.spatialhash_t_Ncell_get
    if _newclass:Ncell = _swig_property(_mylibrary.spatialhash_t_Ncell_get, _mylibrary.spatialhash_t_Ncell_set)
    __swig_setmethods__["cells"] = _mylibrary.spatialhash_t_cells_set
    __swig_getmethods__["cells"] = _mylibrary.spatialhash_t_cells_get
    if _newclass:cells = _swig_property(_mylibrary.spatialhash_t_cells_get, _mylibrary.spatialhash_t_cells_set)
    __swig_setmethods__["list"] = _mylibrary.spatialhash_t_list_set
    __swig_getmethods__["list"] = _mylibrary.spatialhash_t_list_get
    if _newclass:list = _swig_property(_mylibrary.spatialhash_t_list_get, _mylibrary.spatialhash_t_list_set)
    def __init__(self): 
        this = _mylibrary.new_spatialhash_t()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _mylibrary.delete_spatialhash_t
    __del__ = lambda self : None;
spatialhash_t_swigregister = _mylibrary.spatialhash_t_swigregister
spatialhash_t_swigregister(spatialhash_t)


def SpatialHash_init(*args):
  return _mylibrary.SpatialHash_init(*args)
SpatialHash_init = _mylibrary.SpatialHash_init

def SpatialHash_destroy(*args):
  return _mylibrary.SpatialHash_destroy(*args)
SpatialHash_destroy = _mylibrary.SpatialHash_destroy

def SpatialHash_Push(*args):
  return _mylibrary.SpatialHash_Push(*args)
SpatialHash_Push = _mylibrary.SpatialHash_Push

def Build_New_Hash(*args):
  return _mylibrary.Build_New_Hash(*args)
Build_New_Hash = _mylibrary.Build_New_Hash

def SpatialHash_Scanall(*args):
  return _mylibrary.SpatialHash_Scanall(*args)
SpatialHash_Scanall = _mylibrary.SpatialHash_Scanall

def SpatialHash_Scan_Cell(*args):
  return _mylibrary.SpatialHash_Scan_Cell(*args)
SpatialHash_Scan_Cell = _mylibrary.SpatialHash_Scan_Cell

def Build_Particle_Graph(*args):
  return _mylibrary.Build_Particle_Graph(*args)
Build_Particle_Graph = _mylibrary.Build_Particle_Graph

def Hypergraph_Push_Edge_np(*args):
  return _mylibrary.Hypergraph_Push_Edge_np(*args)
Hypergraph_Push_Edge_np = _mylibrary.Hypergraph_Push_Edge_np

def Hypergraph_Get_Edge_np(*args):
  return _mylibrary.Hypergraph_Get_Edge_np(*args)
Hypergraph_Get_Edge_np = _mylibrary.Hypergraph_Get_Edge_np

def Hypergraph_Get_View_np(*args):
  return _mylibrary.Hypergraph_Get_View_np(*args)
Hypergraph_Get_View_np = _mylibrary.Hypergraph_Get_View_np
# This file is compatible with both classic and new-style classes.


