#ifndef __H_KERNEL_sample_state
#define __H_KERNEL_sample_state

/*
 * This file autogenerated by kerngen version p7
 * Copyright 2015 
 * Alejandro Francisco Queiruga
 * Lawrence Berkeley National Lab
 */

#include "kernel.h"

extern kernel_t kernel_state;

#endif